warrior-dining/warrior-dining-back

src/main/java/warriordiningback/domain/Code.java
src/main/java/warriordiningback/domain/place/Place.java
src/main/java/warriordiningback/domain/place/PlaceFile.java
src/main/java/warriordiningback/domain/place/PlaceFileRepository.java
src/main/java/warriordiningback/domain/place/PlaceMenu.java
src/main/java/warriordiningback/domain/place/PlaceMenuRepository.java
src/main/java/warriordiningback/domain/place/PlacesRepository.java
src/main/java/warriordiningback/domain/user/User.java

[#5] Entity 및 Repository 추가 -> Place, PlaceMenu, PlaceFile

---

src/main/java/warriordiningback/api/admin/controller/AdminPlaceController.java
src/main/java/warriordiningback/api/admin/controller/AdminUserController.java
src/main/java/warriordiningback/api/admin/dto/AdminFileData.java
src/main/java/warriordiningback/api/admin/service/AdminFileService.java
src/main/java/warriordiningback/api/admin/service/AdminPlaceService.java
src/main/java/warriordiningback/api/admin/service/AdminPlacesServiceImp.java
src/main/java/warriordiningback/api/admin/service/AdminUserService.java
src/main/java/warriordiningback/api/admin/service/AdminUserServiceImp.java
src/main/java/warriordiningback/components/FileComponent.java
src/main/java/warriordiningback/domain/user/RoleRepository.java

[관리자] - 회원 관리, 음식점 관리 - 기능 구현 완료

[#7] [관리자] - 회원 관리, 음식점 관리 - 기능 구현 완료

---

src/main/java/warriordiningback/api/admin/service/AdminPlaceServiceImp.java
src/main/java/warriordiningback/domain/place/PlaceRepository.java

[#9] 파일명 싱크 맞추기

---

src/main/java/warriordiningback/api/admin/controller/AdminPlaceController.java
src/main/java/warriordiningback/api/admin/controller/AdminUserController.java
src/main/java/warriordiningback/api/admin/service/AdminPlaceService.java
src/main/java/warriordiningback/api/admin/service/AdminPlaceServiceImp.java
src/main/java/warriordiningback/api/admin/service/AdminUserService.java
src/main/java/warriordiningback/api/admin/service/AdminUserServiceImp.java
src/main/java/warriordiningback/domain/Code.java
src/main/java/warriordiningback/domain/place/Place.java
src/main/java/warriordiningback/domain/place/PlaceFileRepository.java
src/main/java/warriordiningback/domain/place/PlaceMenu.java
src/main/java/warriordiningback/domain/place/PlaceMenuRepository.java
src/main/java/warriordiningback/domain/place/PlaceRepository.java
src/main/java/warriordiningback/domain/user/User.java
src/main/java/warriordiningback/security/SecurityConfig.java

- 회원 목록 페이지 > 페이징 처리 완료
- 음식점 목록 페이지 > 페이징 처리 완료
- 음식점 상세 페이지 > 수정 기능 완료 
- 수정페이지 > 기존 이미지와 새로 이미지를 추가하는 부분을 분기하여 처리

[#11] <ADMIN> - 회원 관리 , 음식점 관리 페이지 기능 수정

---

src/main/java/warriordiningback/api/restaurant/controller/RestaurantController.java
src/main/java/warriordiningback/domain/place/PlaceInfo.java
src/main/java/warriordiningback/domain/place/PlaceRepository.java

-  사용자화면 음식점 찾기 페이지
-    제네릭 메소드 활용 PlaceInfo
-   음식점 찾기 페이지에 필요한 데이터만 불러오기
-   페이징화 총 10개의 음식점 정보만 불러오기
-   스크롤 관련은 프론트단에서 처리
close #13

[#13] 사용자 음식점 찾기화면 (페이징)

---

src/main/java/warriordiningback/api/restaurant/controller/RestaurantController.java
src/main/java/warriordiningback/api/restaurant/service/RestaurantService.java
src/main/java/warriordiningback/domain/place/PlaceInfo.java

-  사용자 음식점 찾기화면 중복 리스트 처리
- 인터페이스 placeinfo 의 place file 리스트화
- 컨트롤러 로직 변경 - 레포지토리 > 서비스 > 컨트롤러

[#20] 사용자 음식점 찾기화면 중복 리스트 처리

---

src/main/java/warriordiningback/api/admin/controller/AdminInquiryController.java
src/main/java/warriordiningback/api/admin/controller/AdminReservationController.java
src/main/java/warriordiningback/api/admin/controller/AdminReviewController.java
src/main/java/warriordiningback/domain/Code.java
src/main/java/warriordiningback/domain/inquiry/Inquiry.java
src/main/java/warriordiningback/domain/inquiry/InquiryRepository.java
src/main/java/warriordiningback/domain/reservation/Reservation.java
src/main/java/warriordiningback/domain/reservation/ReservationRepository.java
src/main/java/warriordiningback/domain/review/Review.java
src/main/java/warriordiningback/domain/review/ReviewRepository.java
src/main/java/warriordiningback/domain/user/User.java
src/main/java/warriordiningback/security/SecurityConfig.java

- 목록 페이지 출력
- 상세페이지 출력
리뷰 부탁드립니다

[#12] 관리자 문의사항 페이지 작업

---

src/main/java/warriordiningback/api/admin/controller/AdminPlaceController.java
src/main/java/warriordiningback/api/admin/controller/AdminUserController.java
src/main/java/warriordiningback/api/admin/service/AdminFileService.java
src/main/java/warriordiningback/api/admin/service/AdminPlaceService.java
src/main/java/warriordiningback/api/admin/service/AdminPlaceServiceImp.java
src/main/java/warriordiningback/api/admin/service/AdminUserService.java
src/main/java/warriordiningback/api/admin/service/AdminUserServiceImp.java
src/main/java/warriordiningback/components/FileComponent.java
src/main/java/warriordiningback/domain/place/PlaceFileRepository.java
src/main/java/warriordiningback/domain/place/PlaceRepository.java
src/main/java/warriordiningback/domain/user/UserRepository.java

- 회원 목록 페이지 : 검색기능 추가
- 음식점 목록 페이지 : 검색기능 추가

[#19] [관리자] 회원, 음식점 목록 페이지 검색기능 추가

---

src/main/java/warriordiningback/api/admin/controller/AdminReservationController.java
src/main/java/warriordiningback/domain/inquiry/InquiriesAnswer.java
src/main/java/warriordiningback/domain/inquiry/InquiriesAnswerRepository.java
src/main/java/warriordiningback/domain/inquiry/Inquiry.java
src/main/java/warriordiningback/domain/reservation/ReservationRepository.java

[#24]  InquiryAnswer 엔티티 및 레포지토리 업로드 누락으로 인한 긴급 PR 요청

[#24]  InquiryAnswer 엔티티 및 레포지토리 업로드 누락으로 인한 긴급 PR 요청

---

src/main/java/warriordiningback/api/restaurant/controller/RestaurantController.java
src/main/java/warriordiningback/api/restaurant/dto/MonthReservationData.java
src/main/java/warriordiningback/api/restaurant/dto/ReviewData.java
src/main/java/warriordiningback/api/restaurant/dto/TopReservationData.java
src/main/java/warriordiningback/api/restaurant/service/RestaurantService.java
src/main/java/warriordiningback/domain/reservation/ReservationRepository.java
src/main/java/warriordiningback/domain/review/ReviewRepository.java

-  [사용자] 예약 Top, 이달의 맛집 데이터 구현
- 예약 Top 데이터 구현
- 이달의 맛집 데이터구현
- 사용자 리뷰 데이터 구현(삭제 안된 리뷰)

[사용자] 예약 Top, 이달의 맛집 데이터 구현

---

src/main/java/warriordiningback/api/admin/controller/AdminReviewController.java
src/main/java/warriordiningback/api/admin/service/AdminReviewService.java
src/main/java/warriordiningback/api/admin/service/AdminReviewServiceImp.java
src/main/java/warriordiningback/domain/review/ReviewRepository.java

- 전체 리뷰 목록 페이지 : 정렬 기능, 검색 기능 추가
- Controller에서 로직 분리하여 Service에 정의.
- 리뷰 삭제버튼 수정.

[#30] [관리자] 리뷰관리 - 리뷰 전체 목록 페이지

---

src/main/java/warriordiningback/api/admin/service/AdminPlaceServiceImp.java
src/main/java/warriordiningback/domain/user/User.java
src/main/java/warriordiningback/exception/ErrorCode.java

- 음식점 등록시 입력된 유저 EMAIL(로그인된 사용자 X)의 권한 검사 메소드 추가
- 메소드를 통해 유저 권한중 OWNER권한이 없다면 ErrorCode에 등록된 에러 Throw
` //403
OWNER_PERMISSION_DENIED(HttpStatus.FORBIDDEN, "해당 사용자에게 OWNER 권한이 없습니다.")`
- User 엔티티에 권한 검사 관련 메소드 추가
`public boolean hasRole(String role) {
return this.roles.stream()
.anyMatch(r -> r.getRole().equals(role));}`
- AdminPlaceServiceImp에 권한 검사 관련 메소드 추가
`public void hasRole(String email) {
User user = userRepository.findByEmail(email).orElseThrow(()-> new DiningApplicationException(ErrorCode.USER_NOT_FOUND));
if (!user.hasRole("OWNER")) {
throw new DiningApplicationException(ErrorCode.OWNER_PERMISSION_DENIED);
}
}`

[#32] [관리자]  음식점 관리 - 음식점 상세 페이지 등록시 사장님 아이디 입력값 권한 조회

---

src/main/java/warriordiningback/api/admin/controller/AdminInquiryController.java
src/main/java/warriordiningback/api/admin/service/AdminInquiryService.java
src/main/java/warriordiningback/api/admin/service/AdminInquiryServiceImp.java
src/main/java/warriordiningback/api/admin/service/AdminReviewServiceImp.java
src/main/java/warriordiningback/domain/BaseEntity.java
src/main/java/warriordiningback/domain/inquiry/InquiryRepository.java
src/main/java/warriordiningback/domain/place/Place.java
src/main/java/warriordiningback/domain/review/ReviewRepository.java
src/main/java/warriordiningback/exception/ErrorCode.java

[#34] [관리자] 문의사항 관리 - 검색기능

---

src/main/java/warriordiningback/api/admin/controller/AdminReservationController.java
src/main/java/warriordiningback/api/admin/service/AdminReservationService.java
src/main/java/warriordiningback/api/admin/service/AdminReservationServiceImp.java
src/main/java/warriordiningback/domain/CodeRepository.java
src/main/java/warriordiningback/domain/reservation/ReservationRepository.java

- 검색기능
- 상태값으로 정렬
- controller를 service단으로 분리

관리자 예약관리 페이지

---

src/main/java/warriordiningback/api/admin/controller/AdminMainController.java
src/main/java/warriordiningback/api/admin/dto/InquiryCountDto.java
src/main/java/warriordiningback/api/admin/service/AdminMainService.java
src/main/java/warriordiningback/api/admin/service/AdminMainServiceImp.java
src/main/java/warriordiningback/domain/inquiry/InquiryRepository.java
src/main/java/warriordiningback/domain/place/Place.java
src/main/java/warriordiningback/domain/place/PlaceRepository.java
src/main/java/warriordiningback/domain/reservation/ReservationRepository.java
src/main/java/warriordiningback/domain/review/ReviewRepository.java
src/main/java/warriordiningback/domain/user/User.java
src/main/java/warriordiningback/domain/user/UserRepository.java

[#37] [관리자] 메인페이지 - 대시보드 및 주요 통계 데이터 DB 게더링 완료.

---

src/main/java/warriordiningback/api/restaurant/controller/RestaurantController.java
src/main/java/warriordiningback/api/restaurant/dto/MonthReservationData.java
src/main/java/warriordiningback/api/restaurant/dto/TopReservationData.java
src/main/java/warriordiningback/domain/place/Place.java
src/main/java/warriordiningback/domain/place/PlaceDetailInfo.java
src/main/java/warriordiningback/domain/place/PlaceInfo.java
src/main/java/warriordiningback/domain/place/PlaceRepository.java
src/main/java/warriordiningback/domain/reservation/ReservationRepository.java

-  음식점 디테일 페이지 데이터 구현
-  제네릭 사용 음식점 detail 데이터 값 추가
-  이달의 맛집, 예약 top id 값 추가
-  이달의 맛집, 예약 top 레포지토리 id 값 추가

[사용자] 음식점 디테일 페이지 데이터 구현

---

src/main/java/warriordiningback/domain/reservation/ReservationRepository.java

-  해당월에 예약이 가장 많은 음식점의 id값만 추출

[#48] 사용자 이달의 맛집 쿼리 수정

---

src/main/java/warriordiningback/WarriorDiningBackApplication.java
src/main/java/warriordiningback/api/user/controller/UserBookMarkController.java
src/main/java/warriordiningback/api/user/controller/UserReservationController.java
src/main/java/warriordiningback/api/user/dto/BookMarkResponse.java
src/main/java/warriordiningback/api/user/dto/UserReservationListResponse.java
src/main/java/warriordiningback/api/user/service/UserBookMarkService.java
src/main/java/warriordiningback/api/user/service/UserBookMarkServiceImp.java
src/main/java/warriordiningback/api/user/service/UserReservationService.java
src/main/java/warriordiningback/api/user/service/UserReservationServiceImp.java
src/main/java/warriordiningback/domain/place/Place.java
src/main/java/warriordiningback/domain/place/PlaceRepository.java
src/main/java/warriordiningback/domain/reservation/ReservationRepository.java
src/main/java/warriordiningback/domain/user/User.java
src/main/java/warriordiningback/domain/user/UserRepository.java
src/main/java/warriordiningback/exception/ErrorCode.java
src/main/resources/JOB.sql

- 예약내역 : 기능 구현
- 즐겨 찾기 : 기능 구현

[사용자] 마이페이지 - 예약 내역, 즐겨 찾기 기능구현

---

src/main/java/warriordiningback/api/restaurant/controller/RestaurantController.java
src/main/java/warriordiningback/api/restaurant/dto/PlaceSearchDto.java
src/main/java/warriordiningback/api/restaurant/service/PlaceSearchService.java
src/main/java/warriordiningback/domain/place/PlaceRepository.java

-  [사용자] 음식점 검색 데이터 구현
-  음식점 Id, Name, Comment, AdressNew, Menu, PlaceFile 데이터 게더링

[사용자] 음식점 검색 데이터 구현

---

src/main/java/warriordiningback/api/restaurant/controller/RestaurantController.java
src/main/java/warriordiningback/api/restaurant/dto/PlaceSearchData.java
src/main/java/warriordiningback/api/restaurant/dto/TopReservationData.java
src/main/java/warriordiningback/api/restaurant/service/PlaceSearchService.java
src/main/java/warriordiningback/domain/reservation/ReservationRepository.java

-  [사용자] 예약 Top 카테고리 기능 구현
-  사용자 예약 Top 음식점 코드 아이디 값 불러오기 추가
-  place entity의 code_id 를 value에 담아서 불러오기
- 사용자 검색 DTO 파일명 변경(기존 파일은 삭제)

[사용자] 예약 Top 카테고리 기능 구현

---

src/main/java/warriordiningback/api/restaurant/dto/MonthReservationData.java
src/main/java/warriordiningback/domain/reservation/ReservationRepository.java

-  [사용자] 이달의맛집 카테고리 필터 구현
-  이달의 맛집 카테고리 코드 추가

[사용자] 이달의맛집 카테고리 필터 구현

---

src/main/java/warriordiningback/api/user/oauth/service/OAuthService.java
src/main/java/warriordiningback/api/user/service/UserService.java
src/main/java/warriordiningback/domain/Code.java
src/main/java/warriordiningback/domain/user/User.java

userEntity 플래그 필드 추가되었고
회원가입시 가입경로에 따른 플래그 값 입력하였습니다
추가로 code_id 네이밍이 겹쳐 데이터베이스 컬럼명으로 들어갈 네임을 code_gender, code_flag로 수정하였습니다
close #63

[#63] userEntity flag 필드 추가, 회원가입 시 플래그 설정

---

src/main/java/warriordiningback/api/admin/service/AdminInquiryServiceImp.java

- 상수로 박혀있던 userId값 -> 로그인된 userId로 받기

관리자 문의사항 답변 유저 값 받아오기

---

src/main/java/warriordiningback/api/user/controller/UserController.java
src/main/java/warriordiningback/api/user/service/UserService.java

마이페이지 내정보 구현 완료
로그인 된 사용자에 따른 정보조회
UserReponse DTO 사용하였습니다.
- ResponseBody
```json
{
"id": 1,
"name": "사용자",
"email": "tao@exemple.com",
"phone": "01012345678",
"roles": [
{
"id": 1,
"role": "USER"
}
],
"createdAt": "2024-10-18 14:50:39",
"updatedAt": "2024-10-18 14:50:39",
"status": true,
"used": true
}
```
close #65

[#65] 마이페이지 내정보 구현

---

src/main/java/warriordiningback/api/restaurant/controller/RestaurantController.java
src/main/java/warriordiningback/api/restaurant/dto/PlaceSearchData.java
src/main/java/warriordiningback/api/restaurant/service/PlaceSearchService.java
src/main/java/warriordiningback/api/restaurant/service/PlaceService.java
src/main/java/warriordiningback/domain/place/PlaceInfo.java
src/main/java/warriordiningback/domain/place/PlaceRepository.java

-  사용자 음식점 전체 필터 기능 구현
- 음식점 전체 필터 쿼리 로직 추가
- 음식점 전체 필터 dto 추가
- 음식점 필터 서비스 로직 추가
- 음식점 검색후 필터 서비스 로직 추가
- 음식점 전체, 검색 필터 파라미터값 추가

[사용자] 음식점 전체 리스트 필터 기능 구현

---

src/main/java/warriordiningback/api/admin/controller/AdminInquiryController.java
src/main/java/warriordiningback/api/admin/service/AdminInquiryService.java
src/main/java/warriordiningback/api/admin/service/AdminInquiryServiceImp.java

- Body의 Map값 String,String -> String,Object로 변경
- 값을 받을때 타입에러가 나서 변경

 관리자 문의사항관리

---

src/main/java/warriordiningback/api/restaurant/controller/RestaurantController.java
src/main/java/warriordiningback/api/restaurant/service/PlaceFilterService.java
src/main/java/warriordiningback/api/restaurant/service/PlaceRatingService.java
src/main/java/warriordiningback/domain/place/PlaceRepository.java

-  [사용자] 음식점 전체리스트 정렬구분
-  전체리스트 가나다 순으로 정렬 처리
-  서비스 클래스 파일 이름 수정

[사용자] 음식점 전체리스트 정렬 처리

---

build.gradle
src/main/java/warriordiningback/api/admin/controller/AdminMainController.java
src/main/java/warriordiningback/api/admin/docs/AdminMainControllerDocs.java
src/main/java/warriordiningback/api/restaurant/controller/RestaurantController.java
src/main/java/warriordiningback/api/restaurant/docs/RestaurantControllerDocs.java
src/main/java/warriordiningback/api/user/controller/UserReservationController.java
src/main/java/warriordiningback/api/user/dto/UserReservationAddRequest.java
src/main/java/warriordiningback/api/user/dto/UserReservationEditRequest.java
src/main/java/warriordiningback/api/user/dto/UserReservationInfoResponse.java
src/main/java/warriordiningback/api/user/dto/UserReservationListResponse.java
src/main/java/warriordiningback/api/user/service/UserReservationService.java
src/main/java/warriordiningback/api/user/service/UserReservationServiceImp.java
src/main/java/warriordiningback/domain/Code.java
src/main/java/warriordiningback/domain/place/PlaceDetailInfo.java
src/main/java/warriordiningback/domain/reservation/Reservation.java
src/main/java/warriordiningback/swagger/SwaggerConfig.java
src/main/resources/application.yml

- 예약 기능 구현 : 추가 , 수정 , 취소
- swagger
- 라이브러리 추가
- config 추가
- docs 파일 일부 등록

[#68] 음식점 예약기능 구현 및 Swagger 추가

---

src/main/java/warriordiningback/api/user/dto/UserReservationAddRequest.java
src/main/java/warriordiningback/api/user/dto/UserReservationListResponse.java
src/main/java/warriordiningback/token/TokenProvider.java

- 예약 목록과 예약 상세페이지에서 예약 시간 Gap 발생 해결

[#80] [사용자] 마이페이지 - 예약 목록과 예약 상세페이지에서 예약 시간 Gap 발생 해결

---

src/main/java/warriordiningback/api/admin/controller/AdminInquiryController.java
src/main/java/warriordiningback/api/admin/service/AdminInquiryService.java
src/main/java/warriordiningback/api/admin/service/AdminInquiryServiceImp.java
src/main/java/warriordiningback/api/code/CodeService.java
src/main/java/warriordiningback/api/user/service/UserService.java
src/main/java/warriordiningback/domain/inquiry/InquiriesAnswer.java
src/main/java/warriordiningback/domain/inquiry/InquiriesAnswerRepository.java
src/main/java/warriordiningback/domain/inquiry/InquiryRepository.java

관리자 문의사항 코드
- 중복 로직 메서드화 처리하여 레이어별로 구분
- 불필요 코드 제거
- 오타 수정
close #84

[#84] 관리자 문의사항 코드 리팩토링

---

src/main/java/warriordiningback/api/restaurant/controller/RestaurantController.java
src/main/java/warriordiningback/api/restaurant/dto/ReviewData.java
src/main/java/warriordiningback/api/restaurant/service/PlaceRatingService.java
src/main/java/warriordiningback/api/restaurant/service/PlaceReviewService.java
src/main/java/warriordiningback/domain/review/ReviewRepository.java

-  [사용자] 메인페이지 리뷰정보 호출 수정
-  최신 리뷰 10개만 불러오는 것으로 수정

[사용자] 메인페이지 리뷰정보 호출 수정

---

src/main/java/warriordiningback/domain/place/PlaceDetailInfo.java
src/main/java/warriordiningback/domain/place/PlaceInfo.java

- 위치 정보 추가하여 프론트에 데이터 Response

[#80] [사용자] 음식점 상세페이지 - 위치 정보 추가

---

src/main/java/warriordiningback/api/admin/controller/AdminReservationController.java
src/main/java/warriordiningback/api/admin/dto/ReservationResponse.java
src/main/java/warriordiningback/api/admin/service/AdminReservationServiceImp.java

-  예약 시간이 DB데이터와  9시간 차이나는  부분 수정
- 로그삭제 + 필요없는 import지우기

관리자 예약 페이지 수정

---

src/main/java/warriordiningback/api/admin/service/AdminInquiryServiceImp.java
src/main/java/warriordiningback/api/admin/service/AdminMainServiceImp.java
src/main/java/warriordiningback/api/admin/service/AdminReservationServiceImp.java
src/main/java/warriordiningback/api/admin/service/AdminReviewServiceImp.java
src/main/java/warriordiningback/api/restaurant/service/PlaceFilterService.java
src/main/java/warriordiningback/api/restaurant/service/PlaceRatingService.java
src/main/java/warriordiningback/api/restaurant/service/PlaceReviewService.java
src/main/java/warriordiningback/api/restaurant/service/PlaceSearchService.java
src/main/java/warriordiningback/api/user/service/UserBookMarkServiceImp.java
src/main/java/warriordiningback/api/user/service/UserInquiryServiceImp.java
src/main/java/warriordiningback/api/user/service/UserReviewServiceImp.java
src/main/java/warriordiningback/domain/inquiry/InquiryQueryRepository.java
src/main/java/warriordiningback/domain/inquiry/InquiryRepository.java
src/main/java/warriordiningback/domain/place/PlaceMenuRepository.java
src/main/java/warriordiningback/domain/place/PlaceQueryRepository.java
src/main/java/warriordiningback/domain/place/PlaceRepository.java
src/main/java/warriordiningback/domain/reservation/ReservationQueryRepository.java
src/main/java/warriordiningback/domain/reservation/ReservationRepository.java
src/main/java/warriordiningback/domain/review/ReviewQueryRepository.java
src/main/java/warriordiningback/domain/review/ReviewRepository.java
src/main/java/warriordiningback/domain/user/UserQueryRepository.java
src/main/java/warriordiningback/domain/user/UserRepository.java

-  [백엔드] 코드 리팩토링
- JAP, JPQL 레포지토리 분리, 연결
- 미사용 레포지토리 제거

[백엔드] 코드 리팩토링

---

src/main/java/warriordiningback/api/owner/controller/OwnerReservationController.java
src/main/java/warriordiningback/api/owner/dto/OwnerReservationListResponse.java
src/main/java/warriordiningback/api/owner/service/OwnerReservationService.java
src/main/java/warriordiningback/api/owner/service/OwnerReservationServiceImp.java
src/main/java/warriordiningback/api/user/controller/UserBookMarkController.java
src/main/java/warriordiningback/api/user/controller/UserReservationController.java
src/main/java/warriordiningback/api/user/service/UserBookMarkService.java
src/main/java/warriordiningback/api/user/service/UserBookMarkServiceImp.java
src/main/java/warriordiningback/api/user/service/UserReservationService.java
src/main/java/warriordiningback/api/user/service/UserReservationServiceImp.java
src/main/java/warriordiningback/domain/reservation/ReservationQueryRepository.java
src/main/java/warriordiningback/domain/reservation/ReservationRepository.java

- 오너 예약 목록 페이지 구현
- Sub > UserDetails 사용

[#94] [오너] 예약목록 페이지 - 오너 예약 목록 페이지 구현, 마이페이지 Sub > UserDetails 사용

---

src/main/java/warriordiningback/api/user/controller/UserInquiryController.java
src/main/java/warriordiningback/api/user/controller/UserReviewController.java
src/main/java/warriordiningback/api/user/service/UserInquiryService.java
src/main/java/warriordiningback/api/user/service/UserInquiryServiceImp.java
src/main/java/warriordiningback/api/user/service/UserReviewService.java
src/main/java/warriordiningback/api/user/service/UserReviewServiceImp.java

[마이페이지] 유저 이메일 유지

---

src/main/java/warriordiningback/api/admin/controller/AdminMainController.java
src/main/java/warriordiningback/api/admin/controller/AdminPlaceController.java
src/main/java/warriordiningback/api/admin/service/AdminPlaceService.java
src/main/java/warriordiningback/api/admin/service/AdminPlaceServiceImp.java
src/main/java/warriordiningback/api/restaurant/service/PlaceFilterService.java
src/main/resources/application.yml

관리자 Place 로직
중복 로직 제거, 불필요 어노테이션 및 명령어 제거
user, code에 해당하는 중복로직 해당 service에 메서드 생성하여 책임 분리
close #104

[#104] 관리자 Place 로직 리팩토링

---

src/main/java/warriordiningback/api/admin/controller/AdminReviewController.java
src/main/java/warriordiningback/api/admin/service/AdminPlaceServiceImp.java
src/main/java/warriordiningback/api/admin/service/AdminReviewService.java
src/main/java/warriordiningback/api/admin/service/AdminReviewServiceImp.java

관리자 리뷰 로직 리팩토링
- 중복로직 메서드 처리하여 재사용 로직으로 변경
- switch문 람다식으로 변경
- 불필요 어노테이션 및 명령어 제거
- Transactional 처리 구분
close #107

[#107] 관리자 review 로직 리팩토링

---

src/main/java/warriordiningback/api/admin/controller/AdminInquiryController.java
src/main/java/warriordiningback/api/admin/controller/AdminMainController.java
src/main/java/warriordiningback/api/admin/controller/AdminReservationController.java
src/main/java/warriordiningback/api/admin/service/AdminReservationService.java
src/main/java/warriordiningback/api/admin/service/AdminReservationServiceImp.java
src/main/java/warriordiningback/token/TokenProvider.java

불필요 어노테이션 제거, findCodeById 레이어 분리
close #109

관리자 reservation 로직 리팩토링

---

src/main/java/warriordiningback/api/admin/controller/AdminUserController.java
src/main/java/warriordiningback/api/user/controller/UserBookMarkController.java
src/main/java/warriordiningback/api/user/controller/UserInquiryController.java
src/main/java/warriordiningback/api/user/controller/UserReservationController.java
src/main/java/warriordiningback/api/user/controller/UserReviewController.java
src/main/java/warriordiningback/api/user/dto/UserReservationAddRequest.java
src/main/java/warriordiningback/api/user/dto/UserReservationEditRequest.java

-  [백엔드] USER Valid 처리
- USER컨트롤러 및 DTO valid 처리
- 파라미터 가독성 처리

[백엔드] api 유저 Valid 처리

---

src/main/java/warriordiningback/api/admin/dto/PlaceRecentResponse.java
src/main/java/warriordiningback/api/admin/service/AdminMainServiceImp.java
src/main/java/warriordiningback/api/user/controller/UserBookMarkController.java
src/main/java/warriordiningback/api/user/controller/UserReservationController.java
src/main/java/warriordiningback/api/user/dto/SignInRequest.java
src/main/java/warriordiningback/api/user/dto/SignUpRequest.java
src/main/java/warriordiningback/api/user/dto/UserReservationAddRequest.java
src/main/java/warriordiningback/api/user/service/UserBookMarkService.java
src/main/java/warriordiningback/api/user/service/UserBookMarkServiceImp.java
src/main/java/warriordiningback/api/user/service/UserReservationService.java
src/main/java/warriordiningback/api/user/service/UserReservationServiceImp.java
src/main/java/warriordiningback/domain/review/ReviewQueryRepository.java
src/main/java/warriordiningback/exception/ErrorCode.java
src/main/java/warriordiningback/token/TokenProvider.java

- 예약 예외 상황 처리 : 음식점 주인이 예약 시 exception 처리
- 즐겨찾기 등록 로직 수정
- email -> 아이디로 명칭 수정
- 생년월일 정규식 패턴 추가

[#105] [백엔드] 코드 수정

---

src/main/java/warriordiningback/api/user/dto/UserInquiryResponse.java
src/main/java/warriordiningback/api/user/service/UserInquiryServiceImp.java
src/main/java/warriordiningback/domain/inquiry/InquiriesAnswerRepository.java

- 관리자 답변이 달린 경우 답변 내용까지 데이터 전달

[#113] [문의사항] 사용자 문의내역

---

src/main/java/warriordiningback/api/owner/controller/OwnerReservationController.java
src/main/java/warriordiningback/api/owner/service/OwnerReservationService.java
src/main/java/warriordiningback/api/owner/service/OwnerReservationServiceImp.java

- 기존 admin 예약 취소 로직로 동작 -> owner 예약 취소 로직 별도 생성

[#118] [오너] 예약관리 - 예약 취소 로직 수정
